name: Package VSIX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install

      - name: Package VSIX
        run: npx @vscode/vsce package

      - name: Upload VSIX as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: remote-runner
          path: "*.vsix"